### PR TITLE
adapt zeta repo

### PR DESCRIPTION
**Pull request by haubi**

### CODE REVIEW

**Review by MatthewKhouzam — COMMENTED** [review]
This is a cool experiment you did, but not for merging, I think.

**Comment by haubi** [comment]
Is there a reason why this repo is named ".eclipsefdn", and not "some-repo-used-to-administrate-other-repos"?

**Comment by fredg02** [comment]
> Is there a reason why this repo is named ".eclipsefdn", and not "some-repo-used-to-administrate-other-repos"?

some-repo-used-to-administrate-other-repos is an awful long name. :clown_face: 
".eclipsefdn" has been chosen to contain Eclipse Foundation specific settings, that might not be limited to Otterdog configurations.

**Comment by netomi** [comment]
the reason it does not work in your case is because you created a fork of the repo.
The way we do the validation does not work in this case, sry for the inconvenience.

**Review by netomi — APPROVED** [review]

**Pull request merged**
