### PR TITLE
fix(security): adding branch protection to zeta

### PR DESCRIPTION
**Pull request by vhemery**

### CODE REVIEW

**Review by MatthewKhouzam — COMMENTED** [review]
Are you sure you want to remove reviewer count? I think you have a merge issue.

**Comment by vhemery** [comment]
Superseded by https://github.com/EclipseConTutorial/.eclipsefdn/commit/1d27e7f80c20b2ff1a65efa4503d1cde667db481

**Review by fedejeanne — CHANGES_REQUESTED** [review]
You removed the protection options of other repositories. Please revert

**Pull request closed without merging**
